version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo INSTALL DEPENDENCIES
      - sudo yum update
      - sudo mvn install
  build:
    commands:
      - echo BUILD APPLICATION
      - sudo mvn compile
      - sudo mvn test
  post_build:
    commands:
      - echo INIT POST BUILD
      - sudo mvn clean package
      - sudo cd target/
      - sudo ls -lha
artifacts:
  files:
    - dslist-0.0.1-SNAPSHOT.jar
  base-directory: target
