version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo INSTALL DEPENDENCIES
      - mvn install
  build:
    commands:
      - echo BUILD APPLICATION
      - mvn compile
      - mvn test
  post_build:
    commands:
      - echo INIT POST BUILD
      - mvn package
      - cd target/
      - ls -lha
artifacts:
  files:
    - dslist-0.0.1-SNAPSHOT.jar
  base-directory: target